version: '3'
services:
  web:
    image: 'php:8.1-apache'
    container_name: lamia-web
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    container_name: lamia-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - lamia
volumes:
  db:
    driver: local
networks: 
  lamia:
    driver: bridge
